spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/taco_cloud
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true

flyway:
  url: jdbc:postgresql://localhost:5432/taco_cloud
  user: postgres
  password: postgres

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG

# Custom properties
taco:
  orders:
    pageSize: 10
